#!/usr/bin/env python3
"""
Remove NotebookLM watermark from PDF.
The watermark is likely a semi-transparent image or text overlay.
"""

import fitz  # PyMuPDF
import sys
import os

def analyze_pdf(input_path):
    """Analyze PDF structure to find potential watermarks."""
    doc = fitz.open(input_path)
    print(f"PDF has {len(doc)} pages")
    
    for page_num in range(len(doc)):
        page = doc[page_num]
        print(f"\n--- Page {page_num + 1} ---")
        
        # Get text blocks
        text_dict = page.get_text("dict")
        
        # Look for text that might be the watermark
        for block in text_dict.get("blocks", []):
            if block.get("type") == 0:  # Text block
                for line in block.get("lines", []):
                    for span in line.get("spans", []):
                        text = span.get("text", "").lower()
                        if "notebook" in text or "generated" in text or "watermark" in text:
                            print(f"  Found potential watermark text: {span.get('text')}")
                            print(f"    Position: {span.get('bbox')}")
                            print(f"    Color: {span.get('color')}")
        
        # Check for images
        images = page.get_images()
        print(f"  Images on page: {len(images)}")
        for img in images:
            xref = img[0]
            print(f"    Image xref: {xref}")
            
        # Check annotations
        annots = page.annots()
        if annots:
            for annot in annots:
                print(f"  Annotation: {annot.type}, {annot.info}")
    
    doc.close()

def remove_watermark_by_redaction(input_path, output_path):
    """
    Try to remove watermark by looking for specific patterns.
    NotebookLM watermarks are typically in corners with low opacity.
    """
    doc = fitz.open(input_path)
    
    watermark_found = False
    
    for page_num in range(len(doc)):
        page = doc[page_num]
        
        # Get all text with details
        text_dict = page.get_text("dict")
        
        for block in text_dict.get("blocks", []):
            if block.get("type") == 0:  # Text block
                for line in block.get("lines", []):
                    for span in line.get("spans", []):
                        text = span.get("text", "")
                        # Check for NotebookLM watermark patterns
                        if any(pattern in text.lower() for pattern in ["notebooklm", "notebook lm", "generated by", "made with"]):
                            bbox = span.get("bbox")
                            print(f"Page {page_num + 1}: Removing '{text}' at {bbox}")
                            # Create redaction annotation
                            page.add_redact_annot(bbox, fill=(255, 255, 255))
                            watermark_found = True
        
        # Apply redactions for this page
        page.apply_redactions()
    
    if watermark_found:
        doc.save(output_path)
        print(f"\nWatermark removed! Saved to: {output_path}")
    else:
        print("\nNo text-based watermark found. Watermark may be an image.")
        doc.save(output_path)
    
    doc.close()
    return watermark_found

def remove_watermark_from_corners(input_path, output_path):
    """
    NotebookLM typically places watermarks in corners.
    This method covers common corner positions.
    """
    doc = fitz.open(input_path)
    
    for page_num in range(len(doc)):
        page = doc[page_num]
        rect = page.rect
        
        # Common watermark positions (corners)
        # Bottom-right corner (most common for NotebookLM)
        corner_height = 30
        corner_width = 200
        
        corners = [
            # Bottom right
            fitz.Rect(rect.width - corner_width, rect.height - corner_height, 
                      rect.width, rect.height),
            # Bottom left
            fitz.Rect(0, rect.height - corner_height, 
                      corner_width, rect.height),
            # Top right
            fitz.Rect(rect.width - corner_width, 0, 
                      rect.width, corner_height),
            # Top left
            fitz.Rect(0, 0, corner_width, corner_height),
        ]
        
        # Search for text in corners
        for corner in corners:
            text = page.get_text("text", clip=corner)
            if "notebooklm" in text.lower() or "notebook" in text.lower():
                print(f"Page {page_num + 1}: Found watermark in corner: '{text.strip()}'")
                # Redact this area with white
                page.add_redact_annot(corner, fill=(1, 1, 1))  # White fill
                page.apply_redactions()
    
    doc.save(output_path)
    doc.close()
    print(f"Processed. Saved to: {output_path}")

def check_and_show_content(input_path):
    """Show content in corners of first page to help identify watermark location."""
    doc = fitz.open(input_path)
    page = doc[0]
    rect = page.rect
    
    print(f"Page size: {rect.width} x {rect.height}")
    
    # Check corners with larger areas
    margin = 100
    
    corners = {
        "Bottom-right": fitz.Rect(rect.width - 250, rect.height - 50, rect.width, rect.height),
        "Bottom-left": fitz.Rect(0, rect.height - 50, 250, rect.height),
        "Top-right": fitz.Rect(rect.width - 250, 0, rect.width, 50),
        "Top-left": fitz.Rect(0, 0, 250, 50),
        "Bottom-center": fitz.Rect(rect.width/2 - 150, rect.height - 50, rect.width/2 + 150, rect.height),
    }
    
    print("\nChecking corners for text:")
    for name, corner in corners.items():
        text = page.get_text("text", clip=corner).strip()
        if text:
            print(f"  {name}: '{text}'")
    
    doc.close()

if __name__ == "__main__":
    input_pdf = "/home/seyominaoto/Videos/AgentAuth/AgentAuth_pitch_deck.pdf"
    output_pdf = "/home/seyominaoto/Videos/AgentAuth/AgentAuth_pitch_deck_nowatermark.pdf"
    
    print("=== Analyzing PDF ===")
    check_and_show_content(input_pdf)
    
    print("\n=== Attempting watermark removal ===")
    found = remove_watermark_by_redaction(input_pdf, output_pdf)
    
    if not found:
        print("\n=== Trying corner-based removal ===")
        remove_watermark_from_corners(input_pdf, output_pdf)
